---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-loader
spec:
  replicas: 1
  selector:
    matchLabels:
      app: data-loader
  template:
    metadata:
      labels:
        app: data-loader
    spec:
      containers:
      - name: pet-store-generator
        image: jayunit100/bigpetstore-load-generator
        command:
          - bash
          - -c
          - "/opt/PetStoreLoadGenerator-1.0/bin/PetStoreLoadGenerator http://localhost:7000/ $STORE_COUNT $CUSTOMERS $SIMULATION_LENGTH"
        env:
          - name: STORE_COUNT
            value: "13"
          - name: CUSTOMERS
            value: "500000"
          - name: SIMULATION_LENGTH
            value: "15000"
      - name: load-gen-kafka-connector
        imagePullPolicy: Always
        image: benfen/dummy-kafka-messenger:latest
        env:
          - name: BROKERS
            value: "kafka-svc:9093"
          - name: STORE_COUNT
            value: "13"
          - name: ZOOKEEPER_URL
            value: "$(ZK_SVC_SERVICE_HOST):$(ZK_SVC_SERVICE_PORT)"
        command:
          - bash
          - -c
          - "/opt/generate-topics.sh $STORE_COUNT && java -jar /opt/dummy-kafka-messenger-1.0-SNAPSHOT.jar"
---
