---
apiVersion: v1
kind: Service
metadata:
  name: rkconn
  labels:
    name: rkconn
spec:
  clusterIP: None
  selector:
    name: rkconn
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rkconn
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rkconn
  template:
    metadata:
      labels:
        app: rkconn
    spec:
      containers:
      - name: load-gen-kafka-connector
        imagePullPolicy: Always
        image: benfen/dummy-kafka-messenger:latest
        env:
          - name: KAFKA_URL
            value: "$(KAFKA_SVC_SERVICE_HOST):$(KAFKA_SVC_SERVICE_PORT)"
          - name: REDIS_URL
            value: "$(REDIS_SVC_SERVICE_HOST)"
          - name: ZOOKEEPER_URL
            value: "$(ZK_SVC_SERVICE_HOST):$(ZK_SVC_SERVICE_PORT)"
        command:
          - sh
          - -c
          - "/opt/redis-kafka-connector.sh"
---
