---
apiVersion: v1
kind: Service
metadata:
  name: rkconn
  labels:
    name: rkconn
spec:
  ports:
    - port: 7001
      name: kafka-transactions
  selector:
    name: rkconn
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rkconn
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rkconn
  template:
    metadata:
      labels:
        app: rkconn
    spec:
      containers:
      - name: load-gen-consumer
        imagePullPolicy: Always
        image: benfen/dummy-kafka-messenger:latest
        env:
          - name: BROKERS
            value: "kafka-svc:9093"
          - name: GROUP_ID
            value: "producer-${HOSTNAME##*-}"
          - name: MESSENGER_MODE
            value: "listen"
          - name: REDIS_HOST
            value: "redis-svc"
          - name: STORE_COUNT
            valueFrom:
              configMapKeyRef:
                name: kapture-config
                key: STORE_COUNT
          - name: ZOOKEEPER_URL
            value: "zk-svc:2181"
        ports:
          - containerPort: 7001
        command:
          - bash
          - -c
          - "java -jar /opt/dummy-kafka-messenger-1.0-SNAPSHOT.jar"
---
